#+OPTIONS: num:nil author:nil timestamp:nil
* Definitions
** Straw Man  Argument
I always think of the Straw Man from The Wizard of Oz, but that's not the real origin. In its simplest definition, straw man is the name of a logical fallacy, which means that if you carefully dissect the argument or statement, it doesn't make sense. Debaters invoke a straw man when they put forth an argument—usually something extreme or easy to argue against—that they know their opponent doesn't support. You put forth a straw man because you know it will be easy for you to knock down or discredit. It's a way of misrepresenting your opponent's position.

It's as if you took a flaming scarecrow, threw it onto the debate floor, yelled “Look, it's my opponent's dangerous straw man,” and then you appeared to save the day by dousing the flames with water. All while your opponent mutters, “That's not my straw man. What just happened?”

— Mignon Fogarty, [[http://www.quickanddirtytips.com/education/grammar/what-is-a-straw-man-argument][Grammar Girl: What Is a Straw Man Argument?]]

** Weak Man Argument
With a “weak man,” you don’t actually fabricate a position, but rather pick the weakest of the arguments actually offered up by people on the other side and treat it as the best or only one they have. ... [T]his is hardly illegitimate all the time, because sometimes the weaker argument is actually the prevalent one. Maybe the best arguments for Christianity are offered up by Thomas Aquinas or St. Augustine, but I doubt there are very many people who are believers because they read On Christian Doctrine. Probably this will be the case with some frequency, if only because the less complex or sophisticated an argument is, the easier it is for lots of people to be familiar with it. On any topic of interest, a three-sentence argument is unlikely to be very good, but it’s a lot more likely to spread.

— Julian Sanchez, [[http://www.juliansanchez.com/2009/07/01/the-weak-man/][The Weak Man]]

** Steel Man Argument

Steelmanning is the opposite of the strawman fallacy. A steelman argument occurs when one intentionally seeks the best form of the opponent's argument, or deriving the strongest possible position from their current arguments. Using this approach encourages pure discussion rather than leading to just another exchange of rehearsed or quietly Googled counterpoints and cheap cop-outs, demonstrates your knowledge of the discussion at hand, and basically makes you a better debater and a better person in general.

— [[http://issuepedia.org/Steel_man_argument][IssuePedia]]

* Why Take the Other Side in an Argument

I think steelmanning makes you a better person. It makes you more charitable, forcing you to assume, at least for a moment, that the people you’re arguing with, much as you ferociously disagree with them or even actively dislike them, are people who might have something to teach you. It makes you more compassionate, learning to treat those you argue with as true opponents, not merely obstacles. It broadens your mind, preventing us from making easy dismissals or declaring preemptive victory, pushing us to imagine all the things that could and might be true in this beautiful, strange world of ours. And it keeps us rational, reminding us that we’re arguing against ideas, not people, and that our goal is to take down these bad ideas, not to revel in the defeat of incorrect people.

— Chana Messinger, "Knocking Down a Steel Man: How to Argue Better"

He who knows only his own side of the case knows little of that. His reasons may be good, and no one may have been able to refute them. But if he is equally unable to refute the reasons on the opposite side, if he does not so much as know what they are, he has no ground for preferring either opinion... Nor is it enough that he should hear the opinions of adversaries from his own teachers, presented as they state them, and accompanied by what they offer as refutations. He must be able to hear them from persons who actually believe them...he must know them in their most plausible and persuasive form.

— John Stuart Mill, On Liberty (1859
)
